def PROMPT_RELEVANT_DFS(user_query, dfs_formatted):
    return (
        "You are given several sampled DataFrames from CSV files (random rows, to help understand the content as a whole). "
        "Your task is to determine which DataFrames are needed to answer the user's question. "
        "\n"
        "IMPORTANT: Be flexible and intelligent when interpreting relevance:\n"
        "- Look for columns that are semantically related to the user's query, not just exact word matches.\n"
        "- For example, if the user asks about 'food spending', include DataFrames with 'Groceries', 'Dining', 'Restaurant', etc.\n"
        "- If the user asks about 'exercise', include DataFrames with 'steps', 'activity', 'calories burned', etc.\n"
        "- Include DataFrames that contain related metrics or categories that could help answer the question.\n"
        "\n"
        "If the answer requires any calculation, lookup, or comparison, include all DataFrames that may contain relevant values, even if the question only mentions one. "
        "Pay special attention to columns that may be related (such as price, amount, salary, id, etc.), and include DataFrames that could be joined or referenced together. "
        "If there is any possibility that a DataFrame could be useful for answering the question, include it. "
        "Err on the side of including more DataFrames rather than missing one. "
        "Respond ONLY with a list of DataFrame names (filenames) that are relevant "
        "Do not use markdown code block. The format should be Python code that can be used with exec(), like this: ['df_x', 'df_y']\n\n"
        "Important: This prompt is supposed to aid on the creation of charts. If the user question does not specifically ask for something that could be used to generate a chart, respond with \"Error: <error explanation>\"\n\n"
        "## User question:\n"
        f"{user_query}\n\n"
        "## Sampled DataFrames:\n"
        f"{dfs_formatted}"
    )

def PROMPT_PYTHON_CODE(user_query, dfs_formatted):
    return (
        "Given several sampled DataFrames from CSV files, your task is to generate ONLY the Python code to create a Streamlit chart that answers the user's question. "
        "Each DataFrame is loaded as dfs['dataframe_name'], so never use the dataframe name directly, always use it as a key of the dfs dict."
        "pandas (pd), numpy (np), Streamlit (st), Altair (alt) and prophet (prophet) are available. DO NOT add imports for them or anything else. "
        "For timeseries charts, always format x-axis labels (dates/times) for maximum human readability, using rotation or formatting as needed to avoid overlap. "
        "You must always create charts using st.altair_chart. Any kind of Altair chart (bar, line, scatter, etc.) may be used as appropriate. "
        "Return only executable Python code—no explanations, comments, or markdown code blocks. "
        "Do NOT use markdown code syntax (such as triple backticks or ```python) in your response. "
        "Comment each line to explain your reasoning for the changes made but keep it very short. "
        "\n"
        "Add a sentence to explain the chart below the chart, use st.expander with the label 'Explain'."
        "\n"
        "IMPORTANT DATE HANDLING:\n"
        "- When using pd.to_datetime(), try to infer the format from the sample data and specify it explicitly (e.g., format='%m/%d/%Y' or format='%m/%d/%Y %I:%M:%S %p').\n"
        "- If you cannot determine the exact format, use infer_datetime_format=True parameter.\n"
        "\n"
        "IMPORTANT: Be flexible and intelligent when interpreting the user's question:\n"
        "- If the user asks for 'food spending' and you have columns like 'Groceries' or 'Dining & Entertainment', use those as they are clearly food-related.\n"
        "- If the user asks for 'exercise' and you have columns like 'steps' or 'activity', use those as they represent exercise.\n"
        "- Look for semantically related columns even if they don't match the exact words in the query.\n"
        "- Combine multiple relevant columns if needed (e.g., sum 'Groceries' + 'Dining & Entertainment' for total food spending).\n"
        "- Only respond with an error if there is truly NO data that could reasonably answer the question.\n\n"
        "## User question: \n"
        f"{user_query}\n\n"
        "## Sampled DataFrames:\n"
        f"{dfs_formatted}"
    )

def PROMPT_IMPROVE_CODE(user_query, code_generated, dfs_formatted, improvement_query):
    prompt = (
        "You are given Python code that generates a Streamlit chart. "
        "The user wants to improve the chart. "
        "Your task is to generate ONLY the improved Python code for the chart, implementing the user's requested improvement as clearly and directly as possible. "
        "\n"
        "IMPORTANT DATE HANDLING:\n"
        "- When using pd.to_datetime(), try to infer the format from the sample data and specify it explicitly (e.g., format='%m/%d/%Y' or format='%m/%d/%Y %I:%M:%S %p').\n"
        "- If you cannot determine the exact format, use infer_datetime_format=True parameter.\n"
        "\n"
        "IMPORTANT: Be helpful and interpret vague requests intelligently:\n"
        "- If the user asks to make it 'professional', 'better', or 'cleaner': improve colors, add titles, axis labels, formatting, remove clutter, use a professional color scheme.\n"
        "- If the user asks to make it 'simple' or 'easy to understand': add clear labels, titles, legends, tooltips, and simplify the visualization.\n"
        "- If the user asks to make it 'prettier' or 'nice': improve aesthetics with better colors, spacing, fonts, and visual appeal.\n"
        "- If the user asks for 'insights' or 'analysis': add annotations, trend lines, averages, or highlight key data points.\n"
        "- Use your best judgment to interpret what the user wants and implement it professionally.\n"
        "- Only reject requests that are completely unrelated to the chart (e.g., 'tell me a joke', 'write a poem').\n"
        "\n"
        "Preserve all existing chart functionality unless the improvement request requires a change. "
        "Comment each line to explain your reasoning for the changes made. "
        "pandas (pd), numpy (np), Streamlit (st), Altair (alt) and prophet (prophet) are available. DO NOT add imports for them or anything else. "
        "You must always create charts using st.altair_chart. Any kind of Altair chart (bar, line, scatter, etc.) may be used as appropriate. "
        "Do not add import statements. Return only executable Python code—no explanations, comments, or markdown code blocks. "
        "Return only executable Python code—no explanations, comments, or markdown code blocks. "
        "Do NOT use markdown code syntax (such as triple backticks or ```python) in your response. "
        "Make very short comments at all lines to explain your reasoning in creating them, but never create a comment block at the start. "
        "Important: You must only respond to requests that iterate the Streamlit chart code (appearance, functionality, layout, translations, or bug fixes). "
        "If the user's request is unrelated to chart iteration, respond with \"Error: <error explanation>\"\n\n"
        f"## Original user query and past iterations queries (separated by /):\n"
        f"{user_query}\n\n"
        "## Sampled DataFrames:\n"
        f"{dfs_formatted}\n\n"
        "## User iteration request:\n"
        f"{improvement_query}\n"
        "## Latest generated code:\n"
        "```\n"
        f"{code_generated}\n"
        "```\n\n"
    )
    return prompt

def PROMPT_IDEAS(dfs_formatted):
    return (
        "Generate 5 chart creation prompts to explore the data in the sampled DataFrames. "
        "Each prompt should be engaging, easy to understand, and focused on creating a specific chart type. "
        "You may suggest joining DataFrames if it creates more interesting visualizations. "
        "The suggested prompts should be both udnerstandable by humans and LLMs. "
        "Format your response as a markdown bullet list with one sentence per prompt. "
        "Use this exact format:\n"
        "- Idea 1: ...\n"
        "- Idea 2: ...\n\n"
        "Do NOT use code blocks or triple backticks.\n\n"
        f"Sampled DataFrames:\n{dfs_formatted}\n\n"
    )